baseURL = "https://jhc90.github.io/"
languageCode = "en-us"
title = "Jochens Docs"
theme = "beautifulhugo"


[[menu.main]]
    identifier = "welcome"
    name = "Willkommen"
    weight = 1
    url = "post/welcome"

# -------------
# -------------
# -------------

[[menu.main]]
    identifier = "aboutme"
    name = "About"
    weight = 10
# -------------
[[menu.main]]
    parent = "aboutme"
    name = "Das Bin ich"
    url = "aboutme/"
    weight = 1

# -------------
[[menu.main]]
    parent = "aboutme"
    name = "Über diese Webseite"
    url = "aboutme/"
    weight = 2

# -------------
# -------------
# -------------


[[menu.main]]
    identifier = "docs"
    name = "Dokumentationen"
    weight = 20

# -------------
# -------------
# -------------

[[menu.main]]
    identifier = "projects"
    name = "Projekte"
    weight = 30


# -------------
# -------------
# -------------

[[menu.main]]
    identifier = "impressum"
    name = "Impressum"
    weight = 40








