baseURL = "https://jhc90.github.io/"
languageCode = "de-de"
title = "Jochen Hollich"
theme = "beautifulhugo"


[[menu.main]]
    identifier = "welcome"
    name = "Willkommen"
    weight = 1
    url = "post/welcome"

# -------------
# -------------
# -------------

[[menu.main]]
    identifier = "about"
    name = "About"
    weight = 10
# -------------
[[menu.main]]
    parent = "about"
    name = "Das Bin ich"
    url = "aboutme/"
    weight = 10

# -------------
[[menu.main]]
    parent = "about"
    name = "Über diese Webseite"
    url = "aboutme/"
    weight = 20

# -------------
[[menu.main]]
    parent = "about"
    name = "Lernpfad"
    url = "/docs/learningPath/"
    weight = 30

# -------------
# -------------
# -------------


[[menu.main]]
    identifier = "docs"
    name = "Dokumentationen"
    weight = 20

# -------------
[[menu.main]]
    parent = "docs"
    name = "Mathe"
    identifier = "mathe"
    url = "/docs/math/"
    weight = 10

# -------------
[[menu.main]]
    parent = "docs"
    name = "Informatik"
    identifier = "info"
    url = "/docs/info/"
    weight = 20

# -------------
[[menu.main]]
    parent = "info"
    name = "Programmieren"
    url = "/docs/info/programmieren"
    weight = 10

# -------------
[[menu.main]]
    parent = "docs"
    name = "Data-Science"
    url = "/docs/ds/"
    weight = 30

# -------------
[[menu.main]]
    parent = "docs"
    name = "Domänen"
    url = "/docs/domain/"
    weight = 40

# -------------
# -------------
# -------------

[[menu.main]]
    identifier = "projects"
    name = "Projekte"
    weight = 30

[[menu.main]]
name = "Our Teas"
identifier = "ourteas"
url = "/categories/"
weight = 100
hasChildren = true

[[menu.main]]
name = "Black tea"
parent = "ourteas"
identifier = "blacktea"
url = "/categories/black-tea/"
hasChildren = true

[[menu.main]]
name = "Black tea leafe"
parent = "blacktea"
identifier = "blacktealeaf"
url = "/categories/black-tea/blacktealeaf"



# -------------
# -------------
# -------------

[[menu.footer]]
    identifier = "impressum"
    name = "Impressum"
    url = "/impressum/"








